## 5. Implementation Code

Here is the calorie calculation example from the transcript.


In [1]:
import numpy as np

def broadcasting_demo():
    # 1. Setup Data (3 rows x 4 columns)
    # Rows: Carbs, Protein, Fat
    # Cols: Apple, Beef, Eggs, Potato
    A = np.array([
        [56.0, 0.0, 4.4, 68.0],
        [1.2, 104.0, 52.0, 8.0],
        [1.8, 135.0, 99.0, 0.9]
    ])
    
    print(f"Original Matrix A (Shape {A.shape}):\n{A}")
    
    # 2. Sum Vertically (axis=0)
    # Result should be (4,) or (1,4) depending on implementation
    cal = A.sum(axis=0)
    print(f"\nTotal Calories per food (cal): {cal}")
    
    # 3. BROADCASTING HAPPENS HERE
    # We divide (3,4) by (4,)
    # Python expands 'cal' to match 'A'
    percentage = 100 * A / cal.reshape(1, 4)
    
    print(f"\nPercentage of Calories (Shape {percentage.shape}):\n{percentage}")
    # Verification: Apple Carbs % should be 56/59 * 100 ≈ 94.9%

if __name__ == "__main__":
    broadcasting_demo()

Original Matrix A (Shape (3, 4)):
[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]

Total Calories per food (cal): [ 59.  239.  155.4  76.9]

Percentage of Calories (Shape (3, 4)):
[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
