In [1]:
import numpy as np

def convolve_2d(image, filter_kernel):
    """
    Performs a valid 2D convolution between an image and a filter.
    """
    h_img, w_img = image.shape
    h_filter, w_filter = filter_kernel.shape
    
    # Calculate output dimensions (n - f + 1)
    h_out = h_img - h_filter + 1
    w_out = w_img - w_filter + 1
    
    output = np.zeros((h_out, w_out))
    
    # Slide the filter over the image
    for i in range(h_out):
        for j in range(w_out):
            # Extract the region of interest (ROI)
            region = image[i:i+h_filter, j:j+w_filter]
            # Perform element-wise multiplication and sum
            output[i, j] = np.sum(region * filter_kernel)
            
    return output

# ==========================================
# Example 1: The Specific Calculation (Math Check)
# ==========================================
print("--- Example 1: Specific Math Check ---")
# The 6x6 input matrix from the video/text
input_matrix = np.array([
    [3, 0, 1, 2, 7, 4],
    [1, 5, 8, 9, 3, 1],
    [2, 7, 2, 5, 1, 3],
    [0, 1, 3, 1, 7, 8],
    [4, 2, 1, 6, 2, 8],
    [2, 4, 5, 2, 3, 9]
])

# The Vertical Edge Filter (3x3)
vertical_filter = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

result_1 = convolve_2d(input_matrix, vertical_filter)

print("Input (Top-Left 3x3 subset):")
print(input_matrix[:3, :3])
print("\nFilter:")
print(vertical_filter)
print("\nCalculation for first pixel: (3*1 + 0*0 + 1*-1) + (1*1 + 5*0 + 8*-1) + (2*1 + 7*0 + 2*-1)")
print(f"Expected Result: -5")
print(f"Actual Computed Result (Top-Left pixel): {result_1[0,0]}")
print("\nFull Output Matrix (4x4):")
print(result_1)


# ==========================================
# Example 2: Vertical Edge Detection Intuition
# ==========================================
print("\n\n--- Example 2: Vertical Edge Detection (10s and 0s) ---")
# Create 6x6 image: Left half 10, Right half 0
image_vertical = np.zeros((6, 6))
image_vertical[:, :3] = 10

print("Input Image (Simplified):")
print(image_vertical)

# Apply the same vertical filter
result_vertical = convolve_2d(image_vertical, vertical_filter)

print("\nOutput (Detecting the vertical edge in the center):")
print(result_vertical)
# You will see '30's in the middle, indicating a strong positive vertical edge.


# ==========================================
# Example 3: Horizontal Edge Detection
# ==========================================
print("\n\n--- Example 3: Horizontal Edge Detection ---")
# Create 6x6 image: Top half 10, Bottom half 0
image_horizontal = np.zeros((6, 6))
image_horizontal[:3, :] = 10

# Create Horizontal Filter (Rotated 90 degrees)
horizontal_filter = np.array([
    [1, 1, 1],
    [0, 0, 0],
    [-1, -1, -1]
])

print("Input Image (Horizontal Split):")
print(image_horizontal)
print("\nHorizontal Filter:")
print(horizontal_filter)

# Apply horizontal filter
result_horizontal = convolve_2d(image_horizontal, horizontal_filter)

print("\nOutput (Detecting the horizontal edge):")
print(result_horizontal)

--- Example 1: Specific Math Check ---
Input (Top-Left 3x3 subset):
[[3 0 1]
 [1 5 8]
 [2 7 2]]

Filter:
[[ 1  0 -1]
 [ 1  0 -1]
 [ 1  0 -1]]

Calculation for first pixel: (3*1 + 0*0 + 1*-1) + (1*1 + 5*0 + 8*-1) + (2*1 + 7*0 + 2*-1)
Expected Result: -5
Actual Computed Result (Top-Left pixel): -5.0

Full Output Matrix (4x4):
[[ -5.  -4.   0.   8.]
 [-10.  -2.   2.   3.]
 [  0.  -2.  -4.  -7.]
 [ -3.  -2.  -3. -16.]]


--- Example 2: Vertical Edge Detection (10s and 0s) ---
Input Image (Simplified):
[[10. 10. 10.  0.  0.  0.]
 [10. 10. 10.  0.  0.  0.]
 [10. 10. 10.  0.  0.  0.]
 [10. 10. 10.  0.  0.  0.]
 [10. 10. 10.  0.  0.  0.]
 [10. 10. 10.  0.  0.  0.]]

Output (Detecting the vertical edge in the center):
[[ 0. 30. 30.  0.]
 [ 0. 30. 30.  0.]
 [ 0. 30. 30.  0.]
 [ 0. 30. 30.  0.]]


--- Example 3: Horizontal Edge Detection ---
Input Image (Horizontal Split):
[[10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.